
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzers;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int Input = 27;
  public static final int BracketClose = 13;
  public static final int GreaterThan = 11;
  public static final int Textarea = 28;
  public static final int LessEqual = 10;
  public static final int Plus = 3;
  public static final int Button = 34;
  public static final int h1End = 71;
  public static final int TextAlign = 39;
  public static final int Minus = 4;
  public static final int Div = 5;
  public static final int Mult = 6;
  public static final int height = 79;
  public static final int href = 43;
  public static final int Title = 23;
  public static final int DivHtmlEnd = 69;
  public static final int LessThan = 9;
  public static final int TitleEnd = 62;
  public static final int FontSizeSentence = 46;
  public static final int Color = 37;
  public static final int Link = 24;
  public static final int SelectEnd = 67;
  public static final int FunctionName = 80;
  public static final int Option = 30;
  public static final int ParClose = 19;
  public static final int Span = 26;
  public static final int classSentence = 74;
  public static final int BodyEnd = 64;
  public static final int ImageSize = 73;
  public static final int TextareaEnd = 66;
  public static final int src = 77;
  public static final int Body = 25;
  public static final int LinkEnd = 63;
  public static final int pEnd = 72;
  public static final int ButtonEnd = 70;
  public static final int p = 36;
  public static final int BracketOpen = 12;
  public static final int ColsSentence = 50;
  public static final int OptionEnd = 68;
  public static final int altSentence = 53;
  public static final int id = 41;
  public static final int Head = 22;
  public static final int Img = 32;
  public static final int Column = 76;
  public static final int onclickSentence = 52;
  public static final int And = 15;
  public static final int TextAlignSentence = 59;
  public static final int Or = 16;
  public static final int name = 42;
  public static final int EOF = 0;
  public static final int ColorSentence = 45;
  public static final int HeadEnd = 61;
  public static final int FontSize = 56;
  public static final int Hexadecimal = 55;
  public static final int NotEqual = 8;
  public static final int Type = 40;
  public static final int Br = 33;
  public static final int FontFamily = 38;
  public static final int LinkHtml = 58;
  public static final int GreaterEqual = 14;
  public static final int SpanEnd = 65;
  public static final int error = 1;
  public static final int Row = 75;
  public static final int width = 78;
  public static final int Quotes = 20;
  public static final int h1 = 35;
  public static final int Select = 29;
  public static final int Number = 54;
  public static final int Background = 44;
  public static final int TextAliginSentence = 48;
  public static final int RowsSentence = 51;
  public static final int Not = 17;
  public static final int ParOpen = 18;
  public static final int Text = 57;
  public static final int Assign = 2;
  public static final int HtmlEnd = 60;
  public static final int Equal = 7;
  public static final int Html = 21;
  public static final int FontFamilySentence = 47;
  public static final int TypeSentence = 49;
  public static final int DivHtml = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Assign",
  "Plus",
  "Minus",
  "Div",
  "Mult",
  "Equal",
  "NotEqual",
  "LessThan",
  "LessEqual",
  "GreaterThan",
  "BracketOpen",
  "BracketClose",
  "GreaterEqual",
  "And",
  "Or",
  "Not",
  "ParOpen",
  "ParClose",
  "Quotes",
  "Html",
  "Head",
  "Title",
  "Link",
  "Body",
  "Span",
  "Input",
  "Textarea",
  "Select",
  "Option",
  "DivHtml",
  "Img",
  "Br",
  "Button",
  "h1",
  "p",
  "Color",
  "FontFamily",
  "TextAlign",
  "Type",
  "id",
  "name",
  "href",
  "Background",
  "ColorSentence",
  "FontSizeSentence",
  "FontFamilySentence",
  "TextAliginSentence",
  "TypeSentence",
  "ColsSentence",
  "RowsSentence",
  "onclickSentence",
  "altSentence",
  "Number",
  "Hexadecimal",
  "FontSize",
  "Text",
  "LinkHtml",
  "TextAlignSentence",
  "HtmlEnd",
  "HeadEnd",
  "TitleEnd",
  "LinkEnd",
  "BodyEnd",
  "SpanEnd",
  "TextareaEnd",
  "SelectEnd",
  "OptionEnd",
  "DivHtmlEnd",
  "ButtonEnd",
  "h1End",
  "pEnd",
  "ImageSize",
  "classSentence",
  "Row",
  "Column",
  "src",
  "width",
  "height",
  "FunctionName"
  };
}

